### PR TITLE
Correct barcode height if no human readable

### PR DESCRIPTION
**Pull request by Muraveiko**
Removes empty space at the bottom of the barcode

### CODE REVIEW

**Comment by gredler** [comment]
Usually "texts" will be empty if "humanReadableLocation" was set to NONE, so the code works as is. See e.g. src/test/resources/uk/org/okapibarcode/backend/code11/human-readable-location-none.{properties,png} where the PNG file is sized correctly (no bottom space) when HRL is set to NONE. Can you provide a test that fails without this change?

**Comment by Muraveiko** [comment]
https://github.com/woo-j/OkapiBarcode/blob/master/src/main/java/uk/org/okapibarcode/backend/Symbol.java#L328
return symbol_height + **getHumanReadableHeight()** + (2 * quietZoneVertical);
https://github.com/woo-j/OkapiBarcode/blob/master/src/main/java/uk/org/okapibarcode/backend/Symbol.java#L338
In my opinion, it’s right not to add it in the previous function.
In the case when the HRI is disabled, should it return zero?

**Comment by gredler** [comment]
Yes, getHumanReadableHeight() always returns 0 when HRL = NONE (since texts will always be empty). If you know of any examples where this is not the case then it would be a bug, and a testcase for the relevant scenario would be welcome. Otherwise, as is, I don't see a need to change anything here.

**Comment by gredler** [comment]
Closing this PR, since the change doesn't seem necessary. Feel free to comment if you disagree and have a test case that we can look at.

**Pull request closed without merging**
