### PR TITLE
Option to choose GS separator as GS1 field separator for DataMatrix

### PR DESCRIPTION
**Pull request by mabsofxanadu**
changed based on:
https://sourceforge.net/p/zint/code/merge-requests/7/

### CODE REVIEW

**Comment by gredler** [comment]
Same request made to Zint under this ticket: https://sourceforge.net/p/zint/tickets/139/

Conclusion seems to have been that the Russian Pharma-Code does actually require this feature.

Harald's response to the Zint request:

> May I ask some time to find the status of the decrete by the responsible committe ISO/IEC SC31 WG2. I will clarify this in the next meeting (june 2019).

We will probably follow Harald's lead on this after the June meeting.

**Comment by mabsofxanadu** [comment]
Hi,
any news?
on zint side it has been merged.
thanks

**Comment by gredler** [comment]
Still on my radar, but no time to review in the immediate future.

Zint commit here: https://sourceforge.net/p/zint/code/ci/cb3eea2ba02888ed9da1e40a25f58aa4fa0813f9/

**Comment by gredler** [comment]
It looks like the Russian Pharmacode standard has itself become more standards-compatible, and now accepts FNC1 separators.

https://sourceforge.net/p/zint/mailman/message/37099385/

Closing this PR as no longer necessary -- please comment if you have different information.

**Pull request closed without merging**
