### PR TITLE
HTML5 SVG: removes formatting, adds shape-rendering

### PR DESCRIPTION
**Pull request by botcoder**
Allows SVG to be used inline in HTML5 pages, by:

* Removing all formatting from the generated SVG (see _testCode25Inline_)
* Adding browser rendering options (see _ShapeRendering_)
* Allowing the user to suppress XML headers (unnecessary in HTML5)

The motivation for "publicizing" _ExtendedOutputStreamWriter_ was to accomplish this goal with minimal changes to the codebase and keeping backwards compatibility.

Besides, the current impl. relies on internal synchronization (see _OutputWriter_), which can now be replaced by a simple _Appendable_ for performance reasons.

### CODE REVIEW

**Comment by botcoder** [comment]
Also fixes #66

**Comment by gredler** [comment]
Thanks for the contribution, but I think this PR tries to do too much in one go.

Making the XML prolog optional sounds like a good idea to me, and I've added that one piece to the code.

Removing the formatting doesn't really seem necessary -- is this something you can live without?

Finally, the shape rendering option seems interesting, but I haven't personally run across the need -- can you provide some context? Have you needed to scan barcodes directly from screens and/or print SVG documents, where barcode reading suffered without customizing the shape rendering?

**Comment by botcoder** [comment]
Ok, I may open a new PR, then. I solved my issue by not using SvgRenderer at all, but replacing with my own implementation, using a simple StringBuilder, ie:

```java
static String toSvg(Symbol barcode, int magnification) {
    int width = (barcode.getWidth() * magnification);
    int height = (barcode.getHeight() * magnification);

    StringBuilder writer = new StringBuilder(MAX_SIZE);
    writer
        .append("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"").append(width).append("\" height=\"").append(height)
        .append("\" version=\"1.1\">");
    writer.append("<desc>").append(barcode.getContent()).append("</desc>");
    writer.append("<g id=\"barcode\" fill=\"#000000\">");
    writer
        .append("<rect x=\"0\" y=\"0\" width=\"").append(width).append("\" height=\"").append(height).append("\" fill=\"#ffffff\" />");

    int marginX = (barcode.getQuietZoneHorizontal() * magnification);
    int marginY = (barcode.getQuietZoneVertical() * magnification);

    for (Rectangle2D.Double rect : barcode.getRectangles()) {
      int rectX = (int) (rect.x * magnification) + marginX;
      int rectY = (int) (rect.y * magnification) + marginY;
      int rectW = (int) rect.width * magnification;
      int rectH = (int) rect.height * magnification;
      writer
          .append("<rect x=\"").append(rectX).append("\" y=\"").append(rectY).append("\" width=\"").append(rectW).append("\" height=\"").append(rectH).append("\" />");
    }
    writer.append("</g>");
    writer.append("</svg>");
    return writer.toString();
}
```

**Comment by gredler** [comment]
Makes sense. You might want to sanitize strings before appending them (for security purposes), e.g. barcode.getContent().

Do let me know about your experience with shape rendering. I'm curious whether you've found this to be useful in the past, and in what context.

**Pull request closed without merging**
