### PR TITLE
PDF417: Add support for longer `StructuredAppendFileId`

### LINKED ISSUE #102: `PDF417#setStructuredAppendFileId` limit
Currently, you limit `PDF417#setStructuredAppendFileId` between 0 and 900.

I have not found any specs which says anything about this field and limits, but I can see in my J4L implementation, that the following is assigned, and readers are also able to get that number out of it.

```java
new int[] {
  (int) (Math.random () * 255),
  (int) (Math.random () * 255),
  (int) (Math.random () * 255),
  (int) (Math.random () * 255)
};
```

The impl handles it like this:
```java
for(h = 0; h < this.PDFMacroFileId.length; ++h) {
  tmpBlock[tmpBlockCount++] = this.PDFMacroFileId[h];
}
```

Do you remember why you have used the 900 max? Do you think we can extend this to also allow bigger numbers?

### PR DESCRIPTION
**Pull request by uwolfer**
Resolves #102

### CODE REVIEW

**Comment by gredler** [comment]
I need to think about this a bit more.

On the one hand, I don't think it's a good idea to expose the codeword components of the file ID as individual integers. Codewords are always an internal encoding detail, both for this symbology and for others like QR Codes, Data Matrix and Maxicode. In fact, Data Matrix actually has similar "structured append" functionality, with the Data Matrix file ID being a number that is internally decomposed into two codewords during encoding. Other tools are consistent with this approach in their handling of Macro PDF417 file IDs, and accept [a single number](https://docs.aspose.com/barcode/info-cards/macro-pdf417/) or [a single string](https://www.neodynamic.com/Products/Help/BarcodeSilverlight1.0/html/P_Neodynamic_Silverlight_BarcodeProfessional_Pdf417FileId.htm) that is internally encoded into base-900 codewords. When decoding, ZXing provides the file ID as [a single string](https://github.com/zxing/zxing/blob/zxing-3.5.3/core/src/main/java/com/google/zxing/pdf417/PDF417ResultMetadata.java#L54).

On the other hand, if we ask the user to specify the file ID as a single `long` or `int` or `String`, then for the encode / decode to be transparent (input = output), we would have the interesting limitation that not all numbers between some min value (e.g. `0`) and some max value (e.g. `999_999_999_999`) are valid (e.g. `899899` would be valid, but `900` and `1900` would not be valid). It would be weird (but not deal-breaking) to have to explain that file IDs should be 3, 6, 9 or 12 digits long, and that each triplet should not exceed 899...

I think you're partial to the `int[]` because it's what you've seen in J4L :-) But I think it requires more thought...

As far as testing goes, it would be best (if possible) to add `.properties` files to the test directory, and let `SymbolTest` run them. See the `SymbolTest` JavaDoc for more information. You'll just need to create the top `PROPERTIES` section and run the test. The first test run will populate the expectations (instead of testing), and the subsequent runs will then be able to check against the generated expectations. Just make sure that the generated expectations are correct!

**Comment by uwolfer** [comment]
@gredler I have added tests as you suggested. Also added a test with id `1`, which would have failed in the previous test setup (needs 0 left padding).

I still do not have a strong opinion about how the API should looks like. Once you have an opinion, I am happy to adjust this PR.

**Comment by gredler** [comment]
I've been able to find two other tools that accept user-provided file IDs, one of them takes [a single string](https://www.tec-it.com/Documentation/TBarCode11_NET_Reference/class_t_e_c_i_t_1_1_t_bar_code_1_1_macro_pdf417_a2183a17cf2198f343246d633a2fc5c46.html#a2183a17cf2198f343246d633a2fc5c46) and the other takes [a single int](https://cdn.bytescout.com/help/BytescoutBarCodeSDK/index.html).

Let's make it a single string, which is the most common approach and is nicely compatible with ZXing on the reading side.

The `setStructuredAppendFileId` method will need to validate that the string contains only numbers and that the length is a multiple of 3. We'll also want to validate against a maximum length -- does 15 (i.e. 5 triplets) sound OK?

**Comment by uwolfer** [comment]
> Let's make it a single string, which is the most common approach and is nicely compatible with ZXing on the reading side.

Sounds good, will adjust.

> We'll also want to validate against a maximum length -- does 15 (i.e. 5 triplets) sound OK?

Can do that, but do you see any value added by this arbitrary length limit? Shouldn't this be fully under control of the user, as long as it fits into the codewords?

What do you think about the input: should `1` be possible, or should the user always pass triplets (i.e. `001`)?

**Comment by gredler** [comment]
I'd be strict about requiring triplets, so that it forces the developer to be aware of what exactly is going to be read on the other end.

I'm OK leaving the file ID length limit implicit to the number of codewords that the symbol can hold, but if we go that route we'll definitely want to add a call  to `checkCodewordCount` at the top of `addMacroCodewords`, so that we don't overrun the codeword buffer (like the bug you found a few days ago when trying to encode thousands of bytes).

**Comment by uwolfer** [comment]
@gredler Applied your feedback and pushed another iteration. I was not exactly sure about `checkCodewordCount`, please let me know in case that one is not what you wanted to have.

**Comment by gredler** [comment]
Thanks for the contribution! I may make a few minor tweaks and add a few tests as a final step.

Just to triple check, this gets you another step closer to being able to use Okapi for the Swiss e-tax use case, correct?

**Comment by uwolfer** [comment]
> Thanks for the contribution! I may make a few minor tweaks and add a few tests as a final step.

Thanks for you support on this. Will check for any further improvements to lern out of it.

> Just to triple check, this gets you another step closer to being able to use Okapi for the Swiss e-tax use case, correct?

Yes, exactly. The only one missing is #103 as far as I currently can see. Once that one got landed, it would be awesome if you could tag a new release, and then I could start working and making a change request for the reference implementation / spec of the Swiss e-tax.

**Pull request merged**
