### PR TITLE
Bugfix: support decimal magnification values by rounding up

### PR DESCRIPTION
**Pull request by uksolanki**
When we tried to magnify using decimal value such as 1.2 the barcode image is 'cut' due to width being truncated a bit.
This is fixed by converting width to near integer value using Math.ceil.
Also, add test case to verify the same svg

### CODE REVIEW

**Comment by gredler** [comment]
Thanks for the PR.

I think rounding the dimensions up makes sense, to make sure that no partial content is cut off. Can you update the PR to do the same for the height, for consistency?

We'll need to think about doing the same for the other renderers, but I can look at that myself separately.

**Comment by uksolanki** [comment]
Thank you @gredler . Now can we use new version from maven central repository or snapshot version?

**Comment by gredler** [comment]
I'm not sure when the next release will be. Once we release, it will be available on Maven Central, but until then there is no snapshot version. You'll have to build locally or wait until the release to Maven Central.

**Comment by gredler** [comment]
@uksolanki Version 0.4.7 has been released to Maven Central with this fix.

**Pull request merged**
